server:
  port: 8189
#  servlet:
#    context-path: /market
spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:mydatabase;MODE=MySQL
#    username: sa
#    password:
  application:
    name: shop-client
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    cache: false
  web:
    resources:
      static-locations: file:src/main/resources/static/
  cloud:
    config:
      uri: http://localhost:8888
  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.ws.client.MessageTracing.sent: DEBUG
      org.springframework.ws.server.MessageTracing.sent: DEBUG
      org.springframework.ws.client.MessageTracing.received: TRACE
      org.springframework.ws.server.MessageTracing.received: TRACE

